services:
  api:
    build: .
    container_name: synapseshop-api
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,0.0.0.0"
      DB_NAME: synapseshop
      DB_USER: synapseshop
      DB_PASSWORD: synapseshop
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
    networks:
      - synapseshop-net

  db:
    image: postgres:17-alpine
    container_name: synapseshop-db
    environment:
      POSTGRES_USER: synapseshop
      POSTGRES_PASSWORD: synapseshop
      POSTGRES_DB: synapseshop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapseshop -d synapseshop"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - synapseshop-net

  inventory:
    build: ./inventory
    container_name: synapseshop-inventory
    ports:
      - "8001:8001"
    environment:
      DB_NAME: synapseshop
      DB_USER: synapseshop
      DB_PASSWORD: synapseshop
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - synapseshop-net

volumes:
  pgdata:

networks:
  synapseshop-net: